### ISSUE TITLE
Incorrect parsing of negative integers

### ISSUE THREAD

**Issue by dnicolson** [tyrone-sudeium/st3-binaryplist#4]
The version of `plistlib` included with this package contains a bug with negative integers, `18446744073709551551` is displayed instead of `-65`.

It is fixed in `plistlib` with https://github.com/python/cpython/commit/6db6653bbc0841600248e4d7b7542591067c4157. Is it possible to just remove the included `plistlib` as it is part of the standard library?

**Comment by tyrone-sudeium** [comment]
Hi @dnicolson, yeah it's part of the standard library, and in fact that's where I stole it from. However, it was only added to the standard library in Python 3.4, and Sublime Text 3 still ships with 3.3.6:

```
>>> import sys
>>> sys.version
'3.3.6 (default, Mar 29 2018, 23:30:25) [MSC v.1600 64 bit (AMD64)]'
```

It's fixable, but the `plistlib` will need to be pulled from whichever future version of python has this fixed and be backported to support 3.3, the way I've done with this current version. This will take some time that I can't commit to just now, so you might be in for a wait, otherwise pull requests are welcome!

... in fact reading the diff in the commit you linked, the simplest course would be to apply that patch directly to the `plistlib.py` in this repo.
